# Latex Makefile

all:
	pdflatex obfus.tex && bibtex obfus && pdflatex obfus.tex && pdflatex obfus.tex

clean:
	 rm obfus.aux obfus.bcf obfus.log obfus.out obfus.run.xml obfus.bbl obfus-blx.bib obfus.blg 
